---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tygon
  namespace: k8sdeploy
  labels:
    name: tygon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tygon
  template:
    metadata:
      labels:
        app: tygon
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tygon
          image: ghcr.io/k8sdeploy/tygon:0.4.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DEVELOPMENT
              value: "false"
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tygon-vault-token
                  key: token

---
apiVersion: v1
kind: Service
metadata:
  name: tygon-service
  namespace: k8sdeploy
  labels:
    app: tygon
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: tygon
